# Generated by Django 2.2 on 2020-05-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articlepost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='likes',
        ),
    ]
